name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa todo dia √† meia-noite UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do reposit√≥rio
        uses: actions/checkout@v3

      - name: Gerar snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ThompsonRaul
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit do arquivo gerado na branch main
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Atualiza Snake SVG üêç"
          add: "dist/github-contribution-grid-snake.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
